### ISSUE TITLE
Crash with VanillaFix after updating from 2.1.44 to 2.2.134

### ISSUE THREAD

**Issue by michelegargiulo** [p455w0rd/p455w0rds-Library#26]
Minecraft fails to startup pretty early during load time. Happened after I updated:

p455w0rds library from 2.1.44 to 2.2.134;
Wireless Crafting Terminal from 3.11.88 to 3.12.93;
Wireless Terminal Lib from 1.0.6 to 1.0.28
Dank Null from 1.4.46 to 1.5.71

All are currently the latest versions.

Crash log: 
[2019-06-18-6.log](https://github.com/p455w0rd/p455w0rds-Library/files/3301346/2019-06-18-6.log)

**Comment by GhEppIO82** [comment]
same problem minecraft launcher fail

**Comment by wideblaze** [comment]
me2
https://paste.dimdev.org/ejexejenin.mccrash

**Comment by p455w0rd** [comment]
I'm working on it

**Comment by p455w0rd** [comment]
Here is my test environment where pwlib launches fine. Can I get a pack name/mod list?
![](https://puu.sh/DHIHu/a4d51b014d.png)

**Comment by michelegargiulo** [comment]
I'm using a custom (heavy) pack. If that can help you, I'll send you directly the pack (mods + config folder). For now, here's the modlist:
[listmyfolder.txt](https://github.com/p455w0rd/p455w0rds-Library/files/3303428/listmyfolder.txt)

**Comment by p455w0rd** [comment]
i have a version i can give anyone to test if you wish, just to confirm I have fixed the issue...hop on [discord](https://p455w0rd.net/discord) and i'll send it to ya

**Comment by michelegargiulo** [comment]
Tried that version, still experiencing the same crash

**Comment by wideblaze** [comment]
thank you for posting fix so quickly -- thought I was going to delay the release of my pack or back rev

**Comment by silksight** [comment]
I'm haveing the same issue with the mod pack digsite. worked fine yesterday. here's the crash report:---- Minecraft Crash Report ----
// Don't do that.

Time: 2019-06-19 10:22:21 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from p455w0rd's Library (p455w0rdslib)
Caused by: java.lang.RuntimeException: Error linking program: Vertex info
-----------
0(16) : error C5041: cannot locate suitable resource to bind parameter "lights"

    at p455w0rdslib.LibShaders.createProgram(LibShaders.java:93)
    at p455w0rdslib.LibShaders.reload(LibShaders.java:81)
    at p455w0rdslib.LibShaders.lambda$registerReloadListener$0(LibShaders.java:72)
    at p455w0rdslib.LibShaders$$Lambda$420/1966151020.onResourceManagerReload(Unknown Source)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.registerReloadListener(SimpleReloadableResourceManager.java:121)
    at p455w0rdslib.LibShaders.registerReloadListener(LibShaders.java:71)
    at p455w0rdslib.proxy.ClientProxy.preInit(ClientProxy.java:41)
    at p455w0rdslib.P455w0rdsLib.preInit(P455w0rdsLib.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 873259384 bytes (832 MB) / 1567621120 bytes (1495 MB) up to 2863661056 bytes (2731 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2823 139 mods loaded, 139 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version                  | Source                                             | Signature                                |
       |:----- |:--------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft             | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCH   | mcp                   | 9.42                     | minecraft.jar                                      | None                                     |
       | LCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                 | 14.23.5.2823             | forge-1.12.2-14.23.5.2823.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | foamfixcore           | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCH   | srm-hooks             | 1.12.2-1.0.0             | minecraft.jar                                      | None                                     |
       | LCH   | movillages            | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                         | None                                     |
       | LCH   | forgeendertech        | 1.12.2-4.4.20.1          | ForgeEndertech-1.12.2-4.4.20.1-build.0362.jar      | None                                     |
       | LCH   | adpother              | 1.12.2-1.0.18.0          | AdPother-1.12.2-1.0.18.0-build.0362.jar            | None                                     |
       | LCH   | ctm                   | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                          | None                                     |
       | LCH   | appliedenergistics2   | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | bdlib                 | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
       | LCH   | ae2stuff              | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
       | LCH   | applecore             | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCH   | crafttweaker          | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCH   | mtlib                 | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
       | LCH   | modtweaker            | 4.0.17                   | modtweaker-4.0.17.jar                              | None                                     |
       | LCH   | jei                   | 4.15.0.281               | jei_1.12.2-4.15.0.281.jar                          | None                                     |
       | LCH   | appleskin             | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
       | LCH   | attributefix          | 1.0.4                    | AttributeFix-1.12.2-1.0.4.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | betterbuilderswands   | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar  | None                                     |
       | LCH   | blockcraftery         | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                     | None                                     |
       | LCH   | blockdrops            | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                        | None                                     |
       | LCH   | codechickenlib        | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux          | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | brandonscore          | 2.4.12                   | BrandonsCore-1.12.2-2.4.12.205-universal.jar       | None                                     |
       | LCH   | buildinggadgets       | 2.6.8                    | BuildingGadgets-2.6.8.jar                          | None                                     |
       | LCH   | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
       | LCH   | champions             | 1.12.2-1.0.9             | champions-1.12.2-1.0.9.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | chickenchunks         | 2.4.1.73                 | ChickenChunks-1.12.2-2.4.1.73-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | chisel                | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
       | LCH   | clumps                | 3.1.2                    | Clumps-3.1.2.jar                                   | None                                     |
       | LCH   | colored_water         | 1.12.2-b37               | ColoredWater-1.12.2-b37.jar                        | None                                     |
       | LCH   | compactmachines3      | 3.0.18                   | compactmachines3-1.12.2-3.0.18-b278.jar            | None                                     |
       | LCH   | complexcrops          | v4.1.3                   | Complex Crops 1.12.2-4.1.3.jar                     | None                                     |
       | LCH   | controlling           | 3.0.6                    | Controlling-3.0.6.jar                              | None                                     |
       | LCH   | craftingstation       | 0.0.0                    | CraftingStation-0.0.4.jar                          | None                                     |
       | LCH   | craftingtweaks        | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | LCH   | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCH   | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                      | None                                     |
       | LCH   | custombackgrounds     | 1.0                      | CustomBackgrounds-MC1.12-1.1.1.jar                 | None                                     |
       | LCH   | custommainmenu        | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                  | None                                     |
       | LCH   | customnpcs            | 1.12                     | CustomNPCs_1.12.2(30Jan19).jar                     | None                                     |
       | LCH   | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCE   | p455w0rdslib          | 2.2.134                  | p455w0rdslib-1.12.2-2.2.134.jar                    | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LC    | stg                   | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LC    | theoneprobe           | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | LC    | danknull              | 1.5.71                   | DankNull-1.12.2-1.5.71.jar                         | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LC    | patchouli             | 1.0-19                   | Patchouli-1.0-19.jar                               | None                                     |
       | LC    | deepmoblearning       | 1.12.2-2.5.2             | deepmoblearning-1.12.2-2.5.2-universal.jar         | None                                     |
       | LC    | journeymap            | 1.12.2-5.5.5b7           | journeymap-1.12.2-5.5.5b7.jar                      | None                                     |
       | LC    | defaultoptions        | 9.2.8                    | DefaultOptions_1.12.2-9.2.8.jar                    | None                                     |
       | LC    | ding                  | 1.0.1                    | Ding-1.12.1-1.0.1.jar                              | None                                     |
       | LC    | display               | 1.2.4                    | Display-1.2.4.jar                                  | None                                     |
       | LC    | draconicevolution     | 2.3.22                   | Draconic-Evolution-1.12.2-2.3.22.343-universal.jar | None                                     |
       | LC    | elevatorid            | 1.4.2                    | ElevatorMod-1.12.2-1.4.2.jar                       | None                                     |
       | LC    | enderstorage          | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | zerocore              | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
       | LC    | bigreactors           | 1.12.2-0.4.5.67          | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
       | LC    | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | LC    | fastbench             | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                     | None                                     |
       | LC    | fencejumper           | 1.0.5                    | fencejumper-1.12-1.0.5.jar                         | None                                     |
       | LC    | floodlights           | 1.3.2-14                 | FloodLights-1.12.2-1.3.2-14.jar                    | None                                     |
       | LC    | mcmultipart           | 2.5.3                    | MCMultiPart-2.5.3.jar                              | None                                     |
       | LC    | mekanism              | 1.12.2-9.7.8.379         | Mekanism-1.12.2-9.7.8.379.jar                      | None                                     |
       | LC    | sonarcore             | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                     | None                                     |
       | LC    | fluxnetworks          | 3.0.19                   | fluxnetworks-1.12.2-3.0.19-21.jar                  | None                                     |
       | LC    | foamfix               | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LC    | forgelin              | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
       | LC    | forgemultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | microblockcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
       | LC    | minecraftmultipartcbe | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar       | None                                     |
       | LC    | forgivingvoid         | 1.0.23                   | ForgivingVoid_1.12.2-1.0.23.jar                    | None                                     |
       | LC    | ftblib                | 5.4.3.117                | FTBLib-5.4.3.117.jar                               | None                                     |
       | LC    | ftbutilities          | 5.4.0.97                 | FTBUtilities-5.4.0.97.jar                          | None                                     |
       | LC    | itemfilters           | 1.0.3.12                 | ItemFilters-1.0.3.12.jar                           | None                                     |
       | LC    | ftbquests             | 1.6.1.160                | FTBQuests-1.6.1.160.jar                            | None                                     |
       | LC    | ftbbackups            | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.4.jar                    | None                                     |
       | LC    | trashcansreborn       | 1.1.0                    | GarbageBins-1.1.1.jar                              | None                                     |
       | LC    | gasesframework        | 2.0.0                    | gasesframework-1.12.2-2.0.0-pre1.jar               | None                                     |
       | LC    | gases                 | 2.0.0                    | gases-1.12.2-2.0.0-pre1.jar                        | None                                     |
       | LC    | globalgamerules       | 2.2                      | GlobalGameRules-1.12.2-2.2.7.jar                   | None                                     |
       | LC    | gravestone            | 1.10.2                   | gravestone-1.10.2.jar                              | None                                     |
       | LC    | hotornot              | 1.1.2                    | HotOrNot-1.12-1.1.2-16.jar                         | None                                     |
       | LC    | ichunutil             | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | initialinventory      | 2.0.2                    | InitialInventory-3.0.0.jar                         | None                                     |
       | LC    | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LC    | jaff                  | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                      | None                                     |
       | LC    | justenoughreactors    | 1.1.3.61                 | JustEnoughReactors-1.12.2-1.1.3.61.jar             | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
       | LC    | loottweaker           | 0.0.9                    | LootTweaker-1.12.2-0.0.9.jar                       | None                                     |
       | LC    | jeresources           | 0.9.2.58                 | JustEnoughResources-1.12.2-0.9.2.58.jar            | None                                     |
       | LC    | shadowmc              | 3.8.0                    | ShadowMC-1.12-3.8.0.jar                            | None                                     |
       | LC    | leveluphp             | 1.12.2-1.4.0             | leveluphp-1.12.2-1.4.0.jar                         | None                                     |
       | LC    | lockdown              | 1.0                      | Lockdown-1.12.1-7.0.1-universal.jar                | None                                     |
       | LC    | malisiscore           | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LC    | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | LC    | testdummy             | 1.12                     | MmmMmmMmmMmm-1.12-1.14.jar                         | None                                     |
       | LC    | modnametooltip        | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                   | None                                     |
       | LC    | moreoverlays          | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                     | None                                     |
       | LC    | mousetweaks           | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LC    | naturalabsorption     | 1.0.0_for_mc1.12.2       | naturalabsorption-1.0.0_for_mc1.12.2.jar           | None                                     |
       | LC    | naturescompass        | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | LC    | norecipebook          | 1.2.1                    | noRecipeBook_v1.2.2formc1.12.2.jar                 | None                                     |
       | LC    | omlib                 | 3.1.3-246                | omlib-1.12.2-3.1.3-246.jar                         | None                                     |
       | LC    | openmodularturrets    | 3.1.3-355                | openmodularturrets-1.12.2-3.1.3-355.jar            | None                                     |
       | LC    | oreexcavation         | 1.4.140                  | OreExcavation-1.4.140.jar                          | None                                     |
       | LC    | placebo               | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                           | None                                     |
       | LC    | pneumaticcraft        | 1.12.2-0.11.2-365        | pneumaticcraft-repressurized-1.12.2-0.11.2-365.jar | None                                     |
       | LC    | pollutantpump         | 1.1.0                    | pollutantpump-1.12.2-1.1.0.jar                     | None                                     |
       | LC    | portalgun             | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LC    | realistictorches      | 2.1.1                    | RealisticTorches-1.12.2-2.1.1.jar                  | None                                     |
       | LC    | resourceloader        | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LC    | restrictedportals     | 1.12-0.6.3               | restrictedportals-1.12-0.6.3.jar                   | None                                     |
       | LC    | scarper               | 1.1                      | scarper-1.1.jar                                    | None                                     |
       | LC    | secretroomsmod        | 5.6.4                    | secretroomsmod-1.12.2-5.6.4.jar                    | None                                     |
       | LC    | signedit              | 1.12.2-4                 | signedit-1.12.2-5.jar                              | None                                     |
       | LC    | storagenetwork        | 1.7.7                    | SimpleStorageNetwork-1.12.2-1.7.7.jar              | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LC    | snad                  | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                         | None                                     |
       | LC    | storagedrawers        | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
       | LC    | supersoundmuffler     | 1.0.2.10                 | supersoundmuffler-1.12.2-1.0.2.10.jar              | None                                     |
       | LC    | texfix                | 4.0                      | TexFix V-1.12-4.0.jar                              | None                                     |
       | LC    | toastcontrol          | 1.8.1                    | Toast Control-1.12.2-1.8.1.jar                     | None                                     |
       | LC    | torchmaster           | 1.7.1.74                 | torchmaster_1.12.2-1.7.1.74.jar                    | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LC    | translocators         | 2.5.1.77                 | Translocators-1.12.2-2.5.1.77-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | valkyrielib           | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
       | LC    | universalmodifiers    | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
       | LC    | vanillafix            | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LC    | variedcommodities     | 1.12.2                   | VariedCommodities_1.12.2(15may18.jar               | None                                     |
       | LC    | villagenames          | 3.0.3                    | VillageNames-1.12.2-3.0.3.jar                      | None                                     |
       | LC    | vtt                   | 0.6.4                    | VillagerTrades-1.12-0.6.4.jar                      | None                                     |
       | LC    | watercontrolextreme   | 1.0.0                    | WaterControlExtreme-1.0.2.jar                      | None                                     |
       | LC    | wawla                 | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LC    | wearablebackpacks     | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                 | None                                     |
       | LC    | matteroverdrive       | 0.7.0.0                  | MatterOverdrive-1.12.2-0.7.1.0-universal.jar       | None                                     |
       | LC    | phosphor-lighting     | 1.12.2-0.2.4             | phosphor-1.12.2-0.2.4+build46-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LC    | reauth                | 3.6.0                    | reauth-3.6.0.jar                                   | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LC    | adchimneys            | 1.12.2-3.5.2.0           | AdChimneys-1.12.2-3.5.2.0-build.0362.jar           | None                                     |
       | LC    | hungeroverhaul        | 1.12.2-1.3.3.jenkins148  | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar         | None                                     |
       | LC    | mysticallib           | 1.12.2-1.2.1             | mysticallib-1.12.2-1.2.1.jar                       | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      MekanismCoremod (Mekanism-1.12.2-9.7.8.379.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CorePlugin (ForgeEndertech-1.12.2-4.4.20.1-build.0362.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      LoadingPlugin (AdPother-1.12.2-1.0.18.0-build.0362.jar)
                                        com.endertech.minecraft.mods.adpother.transformers.AcidRain$Vanilla
                                        com.endertech.minecraft.mods.adpother.transformers.AcidRain$DynamicSurroundings
                                        com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Mesh
                                        com.endertech.minecraft.mods.adpother.transformers.AcidRain$Weather2$Render
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$FurnaceDouble
                                        com.endertech.minecraft.mods.adpother.transformers.ActuallyAdditions$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.BetterWithMods$Furnace
                                        com.endertech.minecraft.mods.adpother.transformers.CookingForBlockheads$Oven
                                        com.endertech.minecraft.mods.adpother.transformers.DraconicEvolution$Generator
                                        com.endertech.minecraft.mods.adpother.transformers.EnderIO$StirlingGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$EmberBore
                                        com.endertech.minecraft.mods.adpother.transformers.EmbersRekindled$SteamEngine
                                        com.endertech.minecraft.mods.adpother.transformers.FastFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.FutureMC$AdvancedFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.FloodLights$CarbonFloodlight
                                        com.endertech.minecraft.mods.adpother.transformers.Galacticraft$AutoRocket
                                        com.endertech.minecraft.mods.adpother.transformers.Galacticraft$Buggy
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveCraft$FurnaceTE
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityCokeOven
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityBlastFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveEngineering$TileEntityDieselGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersivePetroleum$Motorboat
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveDiesel
                                        com.endertech.minecraft.mods.adpother.transformers.ImmersiveRailroading$LocomotiveSteam
                                        com.endertech.minecraft.mods.adpother.transformers.Mekanism$FuelwoodHeater
                                        com.endertech.minecraft.mods.adpother.transformers.MoreFurnaces$IronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$InferiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$IntermediumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$PrudentiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SuperiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$SupremiumFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.MysticalAgriculture$UltimateFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.Natura$NetherrackFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.RealisticTorches$BlockTorch
                                        com.endertech.minecraft.mods.adpother.transformers.RFTools$CoalGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.StevesCarts$ModuleCoal
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronAlloyFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileIronFurnace
                                        com.endertech.minecraft.mods.adpother.transformers.TechReborn$TileSolidFuelGenerator
                                        com.endertech.minecraft.mods.adpother.transformers.TinkersConstruct$HeatingStructure
                                        com.endertech.minecraft.mods.adpother.transformers.SimpleGrinder$CoalGrinder
                                        com.endertech.minecraft.mods.adpother.renders.AerometerRender
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockCaughtFire
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockUpdateTick
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$BlockExploded
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$GetSkyColor
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$FurnaceFuelBurned
                                        com.endertech.minecraft.mods.adpother.pollution.WorldData$LavaTouchesWater
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      p455w0rdc0re (p455w0rdslib-1.12.2-2.2.134.jar)
                                        p455w0rdslib.asm.ClassTransformer
                                      LoadingPlugin (AdChimneys-1.12.2-3.5.2.0-build.0362.jar)
                                        com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1.2' Renderer: 'GeForce 6150SE nForce 430/integrated/SSE2'
  AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
  Pulsar/craftingstation loaded Pulses: - TinkerTools (Enabled/Not Forced)
                                        - craftingtweaksIntegration (Enabled/Not Forced)
                                        - theoneprobeIntegration (Enabled/Not Forced)
  List of loaded APIs: * AppleCoreAPI (3.2.0) from AppleCore-mc1.12.2-3.2.0.jar
                       * appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
                       * BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
                       * bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.67.jar
                       * Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
                       * Core (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Blocks (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Constants (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Entities (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Entities|Data (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Entities|Data|Role (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Events (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Handlers (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * Core|Handlers|Data (0.1) from CustomNPCs_1.12.2(30Jan19).jar
                       * CraftingTweaks|API (4.1) from CraftingTweaks_1.12.2-8.1.9.jar
                       * ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
                       * DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.22.343-universal.jar
                       * fluxapi (1.0) from fluxnetworks-1.12.2-3.0.19-21.jar
                       * ForgeEndertechAPI (1.0) from ForgeEndertech-1.12.2-4.4.20.1-build.0362.jar
                       * iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.2.1.jar
                       * jeresources|API (0.9.2.58) from JustEnoughResources-1.12.2-0.9.2.58.jar
                       * journeymap|client-api (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.5b7.jar
                       * JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.15.0.281.jar
                       * MatterOverdrive|API (0.4.1) from MatterOverdrive-1.12.2-0.7.1.0-universal.jar
                       * MekanismAPI|core (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|energy (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|gas (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|infuse (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|laser (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|transmitter (9.7.8) from Mekanism-1.12.2-9.7.8.379.jar
                       * MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.7.8.379.jar
                       * MouseTweaks|API (1.0) from MouseTweaks-2.10-mc1.12.2.jar
                       * PatchouliAPI (6) from Patchouli-1.0-19.jar
                       * PneumaticCraftApi (1.1) from pneumaticcraft-repressurized-1.12.2-0.11.2-365.jar
                       * redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
                       * sonarapi (1.0.1) from sonarcore-1.12.2-5.0.19-20.jar
                       * StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.8.jar
                       * theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.28.jar
                       * valkyrielib.api (1.12.2-2.0.10a) from valkyrielib-1.12.2-2.0.20.1.jar
                       * zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
                       * zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
                       * zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
                       * zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
  Suspected Mods: p455w0rd's Library (p455w0rdslib)
  Launched Version: forge-14.23.5.2823
  LWJGL: 2.9.4
  OpenGL: GeForce 6150SE nForce 430/integrated/SSE2 GL version 2.1.2, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 2x AMD Athlon(tm) II X2 B26 Processor

**Comment by silksight** [comment]
i forgot to mention that i started with the most up to date version of the pack and this mod. when it failed to launch I used the previous version of the pack, still failed. then i tried the previous version of the mod, still failed to start. so that's were i am at. the crash report was the latest try.

**Comment by p455w0rd** [comment]
Silksight, use the actual latest version (the version you are using isn't the latest)..if it still persists, go to p455w0rdsLib.cfg and disable shaders..no idea why this would happen, but this is the solution

**Comment by LeonPhilips** [comment]
@p455w0rd I beg you to look at some issue reports I have been given. I performed a little research which may help you get started.

I have also added a zip with 3 mods required to create crashes. This should make debugging a bit easier.

[CrashCombo.zip](https://github.com/p455w0rd/p455w0rds-Library/files/3417282/CrashCombo.zip)

This is the most detailed issue, and probably most useful for you: https://github.com/TerminatorNL/LagGoggles/issues/71#issuecomment-513765666

It looks like an honest mistake, I would have referenced it, but the `p455w0rdslib.asm` package is not synchronized with the GitHub repository. I suspect that `SafeClassWriter` `getCommonSuperClass()` is the problem. I could be wrong, but it might be a nice pointer for you.
