### ISSUE TITLE
Lighting effects crashes game p455w0rdslib-1.12.2-2.2.151 

### ISSUE THREAD

**Issue by wideblaze** [p455w0rd/p455w0rds-Library#37]
still getting reports of lighting effects crashes after updating to p455w0rdslib-1.12.2-2.2.151 

---
bvierraToday at 4:20 PM
Heya, loving the pack but I keep getting crashes @ the ME system in the flame (https://paste.dimdev.org/atocaliqic.mccrash)
I found that changing the following options in p455w0rdsLib.cfg fixed it:
B:EnableShaders=false
B:EnableVanillaLightingEffects=false
---
I could set these as default but I really like the effects

it doesn't seem to happen often but when it does the only fix is above

**Comment by p455w0rd** [comment]
yeah, I have removed the functionality behind this completely now, so it's fixed in the next update :)

**Comment by wideblaze** [comment]
ok great -- thanks for the quick response!

**Comment by Hanoverfist** [comment]
We have a player experiencing this issue on our Project Ozone 3 server. He's made the above cfg changes (also changed shader setting at bottom of cfg file), reinstalled the pack, checked if he had Optifine or any shaders installed, etc. Done everything I can think of to fix this.

He still receives the following error: https://pastebin.com/m9Xkxmme 

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from p455w0rd's Library (p455w0rdslib)
Caused by: java.lang.RuntimeException: Error creating shader: ERROR: 0:15: 'Error' : Cannot offset into the vector`

Note: It occurs during the initial loading of mods when the pack is launched.

Other players are fine. No idea why just this player is receiving it.

Just wanted to provide this info in case it changes how you resolve this problem.

HanoverFist69

**Comment by ProsperCraft** [comment]
Please push the update, I didn't know about this and updated TownCraft and have tons of users crying to me about crashing from it now.

Same crashes as above CME due to the dynamic light ing.

**Comment by wideblaze** [comment]
hey @ProsperCraft these config changes make this a non-issue for now -- have had them in place for 2 weeks and no new reports of crashes:

    # Enables shader support in dependant mods [default: true]
    B:EnableShaders=false

    # If true, then colored lighting effects will be added to vanilla items, blocks, and tile entities. [default: true]
    B:EnableVanillaLightingEffects=false

**Comment by ProsperCraft** [comment]
Thank you, will push a pack update.

**Comment by desagas** [comment]
This crash is still happening on your build 1.12.2-2.2.156.
